### ISSUE TITLE
UTF-8 and accent letters

### ISSUE THREAD

**Issue by brazilcr** [andergtk/localhost-looking-good#3]
1) accent letters become <?> character...

2) On 'Files to ignore' seems that wild card isn't allowed...

3) When click to go to any sub directory level.. Maybe any 403 (no list allowed) http error treatment could deal better with the msg 403 error itself

**Comment by andergtk** [comment]
I worked to fix this, here are the commits:
1 - 883bcd7
2 - 2c673e3
3 - f6e2732
